name: Hello World

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: Create Hello World file
          run: |
            echo "Hello World ${{ github.sha }}" > hello.txt

        - name: Upload artifact
          uses: actions/upload-artifact@v2
          with:
              name: hello-world
              path: hello.txt