name: Release

on:
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: print github context
          run: echo "${{ toJson(github) }}"

        - name: Download artifact
          uses: actions/download-artifact@v2
          with:
              name: hello-world

        - name: Upload Release Asset
          uses: actions/upload-release-asset@v1
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
              upload_url: ${{ github.event.release.upload_url }}
              asset_path: ./hello.txt
              asset_name: hello.txt
              asset_content_type: text/plain